CREATE TABLE patrons (  
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    first_name VARCHAR2(100) NOT NULL,  
    last_name VARCHAR2(100) NOT NULL,  
    email VARCHAR2(255) UNIQUE,  
    phone VARCHAR2(20),  
    address VARCHAR2(255),
    membership_date DATE DEFAULT SYSDATE
);